config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  def self.search(search)
    where("title || body ILIKE ?", "%#{search}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_markdown, only: [:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC")
    else
      @articles = Article.all.order("created_at DESC")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end

    def set_markdown
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article
  before_action :find_comment, only: [:edit, :update, :destroy]
  def create
    @comment = @article.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save!
      redirect_to article_path(@article)
    else
      flash[:error] = "Error saving the comment"
      redirect_to article_path(@article)
    end
  end

  def edit
  end

  def update
    @comment.content = comment_params
    if @comment.update(comment_params)
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_article
    @article = Article.find(params[:article_id])
  end

  def find_comment
    @comment = @article.comments.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, size: '100x10', id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, size: '100x10', id: :article_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>

  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Title</th>
        <th>Created At</th>
        <th>Author</th>
        <th>Body</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= time_ago_in_words(article.created_at) %></td>
          <td><%= article.user.email %></td>
          <td><%= @markdown.render(article.body).html_safe %></td>
          <td><%= link_to 'Show', article %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if user_signed_in? %>
  <% if @article.user_id == current_user.id %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Delete', article_path, method: :delete, data: { confirm: "Are you sure you want to delete Article #{@article.title} ?"}%> |
  <% end %>
<% end %>
<%= link_to 'Back', articles_path %>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @markdown.render(@article.body).html_safe %>
  <h3>Comments:</h3>
    <%= render @article.comments %>
    <% if user_signed_in? %>
      <%= render 'comments/form' %>
    <% end %>
</p>

app/views/comments/_comment.html.erb
<div><%= comment.content %> <span class="badge badge-pill badge-info"><%= comment.user.email %></span></div>
<% if user_signed_in? %>
  <% if comment.user_id == current_user.id %>
    <%= link_to 'Edit', edit_article_comment_path(comment.article, comment), class: 'btn btn-success' %>
    <%= link_to 'Delete', article_comment_path(comment.article, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?'} %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@article, Comment.new] do |f| %>
  <div class="form-inline">
    <%= f.text_field :content, size: '100x10', placeholder: 'Comment...', class: 'form-controller', required: true %>
    <%= f.submit 'Comment', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <h1>Edit Comment:</h1>
  <%= form_for [@article, @comment] do |f| %>
      <div class="form-inline">
        <%= f.text_field :content, label: 'Comment', size: '100x10', required: true %>
        <%= f.button :submit, class: 'btn btn-success' %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Blog</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_article_path %>">New Article</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-method="delete" href="<%= destroy_user_session_path %>">Log Out</a>
            </li>
          <% else %>
            <li class="nav-item active">
              <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_path %>">Log In</a>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <%= form_tag(articles_path, :method => "get", id: "search-form") do%>
              <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
              <%= submit_tag "Search" %>
          <% end %>
        </form>
      </div>
    </nav>
    <% unless flash.empty? %>
      <div class="container">
        <% flash.each do |key, value| %>
            <%= value %>
        <% end %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>